version: '3.3'
services:
  todotests:
    image: todotests
    environment:
      FRONT_HOST: todofront
    depends_on:
      - todofront
      - todoback
  todofront: 
    image: todofrontend
    ports:
      - 3000:3000
    depends_on: 
    - todobackend
    environment:
      REACT_APP_API_HOST: todoback
  todoback:
    image: todobackend
    ports: 
      - 3001:3001